routes/web.php
<?php

use App\Http\Controllers\ExportController;
use App\Http\Livewire\AsignarController;
use App\Http\Livewire\CashuotController;
use Illuminate\Support\Facades\Route;
use App\Http\Livewire\CategoriesController;
use App\Http\Livewire\CoinsController;
use App\Http\Livewire\PermisosController;
use App\Http\Livewire\PostController;
use App\Http\Livewire\ProductsController;
use App\Http\Livewire\ReportsController;
use App\Http\Livewire\RolesController;
use App\Http\Livewire\UsersController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::middleware(['auth'])->group(function () {
    // Route::get('/dashboard', ['as' => 'user.dashboard', 'uses' => 'DashboardController@index']);
    Route::get('categories', CategoriesController::class);
    Route::get('products',ProductsController::class);
    Route::get('coins', CoinsController::class);
    Route::get('pos', PostController::class);
    Route::get('roles', RolesController::class);
    Route::get('permisos', PermisosController::class);
    Route::get('asignar', AsignarController::class);
    Route::get('users', UsersController::class);
    Route::get('cashout',CashuotController::class);
    Route::get('reports',ReportsController::class);

});
// Reportes PDF
Route::get('report/pdf/{user}/{type}/{f1}/{f2}', [ExportController::class,'reportPDF']);
Route::get('report/pdf/{user}/{type}', [ExportController::class,'reportPDF']);
//Reportes Excel

app/Models/Denomination.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Denomination extends Model
{
    use HasFactory;

    protected $fillable = [
        'type',
        'value',
        'image'
    ];
    /* Accesor para imagen */
    public function getImageAccessorAttribute(){
        if ($this->image != null) {
            $path = public_path('/storage/coins/' . $this->image);
            return file_exists($path) ? 'coins/' . $this->image : 'noimg.jpg';
        }else{
            return 'noimg.jpg';
        }
    }
}

app/Http/Livewire/AsignarController.php
<?php

namespace App\Http\Livewire;

use App\Models\User;
use Livewire\Component;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Livewire\WithFileUploads;
use Livewire\WithPagination;
use Illuminate\Support\Facades\DB;

use function Symfony\Component\String\b;

class AsignarController extends Component
{
    use WithPagination;
    use WithFileUploads;

    public $componentName, $permisosSelected=[], $oldPermisos=[];
    public $role;

    private $pagination = 10;

    public function mount(){
      $this->componentName      = 'Asignar Permisos';
      $this->role               = 'ELEGIR';
    }

    public function paginationView()
    {
      return 'vendor.livewire.bootstrap';
    }
    public function render()
    {
        /* Obtenesmos permisos, orden nombre y paginacion*/
        $permisos = Permission::select('name','id', DB::raw("0 as checked"))
            ->orderBy('id','asc')
            ->paginate($this->pagination);

        if ($this->role != 'ELEGIR') {
            $list = Permission::join('role_has_permissions as rp','rp.permission_id','permissions.id')
                ->where('role_id', $this->role)->pluck('permissions.id')->toArray();
                $this->oldPermisos = $list;
        }

        if ($this->role != 'ELEGIR') {
            foreach ($permisos as $permiso) {
                $role = Role::find($this->role);
                $tienePermiso = $role->hasPermissionTo($permiso->name);
                if ($tienePermiso) {
                    $permiso->checked = 1;
                }
            }
        }
        return view('livewire.asignar.component', [
            'roles'     => Role::orderBy('name', 'asc')->get(),
            'permisos'  => $permisos,
        ])->extends('layouts.theme.app')->section('content');
    }

    protected $listeners = ['revokeAll' => 'removeAll'];

    public function removeAll()
    {
        if ($this->role == 'ELEGIR') {
            $this->emit('sync-error','Selecciona un rol valido');
            return;
        }

        $role = Role::find($this->role);
        $role->syncPermissions([0]);
        $this->emit('removeall',"Se revocaron todos lo permisos al role $role->name");
    }

    public function syncAll()
    {
        if ($this->role == 'ELEGIR') {
            $this->emit('sync-error','Selecciona un rol valido');
            return;
        }
        $role = Role::find($this->role);
        $permisos = Permission::pluck('id')->toArray();
        $role->syncPermissions($permisos);
        $this->emit('syncall',"Se sincronizaron todos lo permisos al role $role->name");
    }

    public function syncPermiso($state, $permisoName)
    {
        if ($this->role != 'ELEGIR') {
            $roleName = Role::find($this->role);
            if ($state) {
                $roleName->givePermissionTo($permisoName);
                $this->emit('permi', "Permiso asignado al rol: $roleName->name");
            }else {
                $roleName->revokePermissionTo($permisoName);
                $this->emit('permi', "Permiso revocado al rol: $roleName->name");
            }
        }else {
            $this->emit('sync-error','Selecciona un rol valido');
        }
    }

}

app/Http/Livewire/CashuotController.php
<?php

namespace App\Http\Livewire;

use App\Models\Sale;
use App\Models\User;
use Carbon\Carbon;
use Livewire\Component;

class CashuotController extends Component
{
    public $from_date, $to_date, $user_id, $total, $items, $sales, $details;

    public function mount(){
        $this->from_date = null;
        $this->to_date = null;
        $this->user_id = 0;
        $this->total = 0;
        $this->sales = [];
        $this->details = [];
    }
    public function render()
    {
        return view('livewire.cashout.component', [
            'users' => User::orderBy('name','asc')->get()
            ])
            ->extends('layouts.theme.app')
            ->section('content');
    }

    public function consultar()
    {
        $fi = Carbon::parse($this->from_date)->format('Y-m-d') . ' 00:00:00';
        $ff = Carbon::parse($this->to_date)->format('Y-m-d') . ' 23:59:59';

        $this->sales = Sale::whereBetween('created_at',[$fi,$ff])
            ->where('status','PAID')
            ->where('user_id', $this->user_id)->get();

            $this->total = $this->sales ? $this->sales->sum('total') : 0 ;
            $this->items = $this->sales ? $this->sales->sum('items') : 0 ;

        if ($this->sales->count() <= 0) {
            $this->emit('consulta-error','No hay ventas en la consulta');
        }else {
            $this->emit('consulta-ok','Consulta exitosa!');
        }

    }


    public function viewDetails(Sale $sale)
    {
        $fi = Carbon::parse($this->from_date)->format('Y-m-d') . ' 00:00:00';
        $ff = Carbon::parse($this->to_date)->format('Y-m-d') . ' 23:59:59';

        $this->details = Sale::join('sale_details as d','d.sale_id','sales.id')
            ->join('products as p','p.id','d.product_id')
            ->select('d.sale_id','p.name as product','d.quantity','d.price')
            ->whereBetween('sales.created_at', [$fi,$ff])
            ->where('sales.status','PAID')
            ->where('sales.user_id', $this->user_id)
            ->where('sales.id', $sale->id)
            ->get();


        $this->emit('item-modal-show', 'Mostar vista details');
    }


    public function print()
    {
        # code...
    }
}

app/Http/Livewire/CategoriesController.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\Category;
use Livewire\WithFileUploads; //trait
use Livewire\WithPagination; //trait

class CategoriesController extends Component
{

	use WithFileUploads;
	use WithPagination;

	public $selected_id, $name, $description, $image,
		$pageTitle, $componentName, $search;
	private $pagination = 5;

	public function mount()
	{
		$this->pageTitle = 'Listado';
		$this->componentName = 'Categorias';
	}

	public function paginationView()
	{
		return 'vendor.livewire.bootstrap';
	}

	public function render()
	{
		if (strlen($this->search) > 0) {
			$data = Category::where('name', 'like', '%' . $this->search . '%')
				->paginate($this->pagination);
		} else {
			$data = Category::orderBy('id', 'desc')
				->paginate($this->pagination);
		}
		// echo '<pre>';
		// print_r($data);
		// die();
		// $data = Category::all();
		return view('livewire.category.categories', ['data' => $data])
			->extends('layouts.theme.app')
			->section('content');
	}

	public function edit($id)
	{
		// error_log('Edit categories');
		// error_log($id);
		$record = Category::find($id, ['id', 'name', 'description', 'image']);
		// echo '<pre>'; print_r($record);
		if (isset($record)) {
            $this->selected_id  = $record->id;
			$this->name         = $record->name;
			$this->description  = $record->description;

            /* BEGIN imagen default en el Form categories */
            // $image = new \App\Models\Category();
            // $this->image        = $image->getImageAccessorAttribute();
            $path = public_path('/storage/categories/' . $record->image);
            if (file_exists($path)) {
                $this->image = 'categories/' . $record->image;
            }
            else {
                $this->image = 'noimg.jpg';
            }
            if ($record->image == null) {
                $this->image = 'noimg.jpg';
            }
            /* END imagen en el Form categories */

			$this->emit('modal-show-item', 'show modal!');
		}
	}

	public function store()
	{
		$rules = [
			'name'          => 'required|unique:categories|min:3',
			'description'   => 'required',
            'image'         => 'max:1024'
		];
		$messages = [
			'name.required'         => 'El nombre de la categoria es requerido',
			'name.unique'           => 'La categoria ya existe',
			'name.min'              => 'El nombre debe tener al menos 3 caracteres',
			'description.required'  => 'La descripcion es requerida',
            'image.max'             => 'El tamaño maximo es 1 mega'
		];

		$this->validate($rules, $messages);

		$data = Category::create([
			'name'          => strtoupper($this->name),
			'description'   => $this->description,
		]);
		// dd($this->image);
		if ($this->image) {
			$customFileName = uniqid() . '_.' . $this->image->extension();
			$this->image->storeAs('public/categories/', $customFileName);
			$data->image = $customFileName;
			$data->save();
		}
		// $this->resetErrorBag();
		$this->resetUI();
		$this->emit('item-added', 'Categoria Registrada');
	}

	public function update()
	{
		$rules = [
			'name'          => "required|min:3|unique:categories,name,{$this->selected_id}",
			'description'   => 'required',
            'image'         => 'max:1024'
		];

		$messages = [
			'name.required'         => 'El nombre es requerido',
			'name.min'              => 'El nombre debe tener al menos 3 caracteres',
			'name.unique'           => 'El nombre de la categoria ya existe',
			'description.required'  => 'La descripcion es requerida',
            'image.max'             => 'El tamaño maximo es 1 mega'
		];

		$this->validate($rules, $messages);

		$data = Category::find($this->selected_id);
		$data->update([
			'name'          => strtoupper($this->name),
			'description'   => $this->description,
		]);
		// echo '<pre>';
		// print_r($this->image);
		if ($this->image && !is_string($this->image)) {
			$customFileName = uniqid() . '_.' . $this->image->extension();
			$this->image->storeAs('public/categories/', $customFileName);
			$imageName = $data->image;

			$data->image = $customFileName;
			// error_log($data->image);
			$data->save();

			if ($imageName != null) {
				$path = public_path('/storage/categories/' . $imageName);
				// error_log($path);
				if (file_exists($path)) {
					// error_log('unlink');
					unlink($path);
				}
			}
		}

		// $this->resetValidation();
		// $this->reset(['name','search','selected_id','iamge']); //MISMO resetUI()
		$this->resetUI();
		$this->emit('item-update', 'Categoria Actualizada!');
	}

	/* Escuchar evento para eliminar desde font-end con js */

	protected $listeners = [
		'deleteRow' => 'destroy',
	];

	public function destroy($id)
	{
		$data = Category::find($id);
		// dd($data);
		if (isset($data)) {
			$imageName = $data->image;
			$data->delete();

			if ($imageName != null) {
				$path = public_path('/storage/categories/' . $imageName);
				// error_log($path);
				if (file_exists($path)) {
					// error_log('unlink');
					unlink($path);
				}
			}
			$this->resetUI();
			$this->emit('item-deleted', 'Categoria Eliminada!');
		} else {
			$this->emit('item-deleted', 'Error no se encuentra el registro');
		}
	}

	public function resetUI(){
		$this->resetValidation();
        $this->resetPage();

		$this->selected_id  = 0;
		$this->name         = '';
		$this->description  = '';
		$this->search       = '';
		$this->image        = null;
	}
}

app/Http/Livewire/PermisosController.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Livewire\WithFileUploads;
use Livewire\WithPagination;
use App\Models\User;
use Illuminate\Support\Facades\DB;

class PermisosController extends Component
{
  use WithPagination;
  use WithFileUploads;

  public $selected_id, $componentName, $pageTitle, $search;
  public $name;

  private $pagination = 10;

  public function mount(){
    $this->componentName    = 'Permisos';
    $this->pageTitle        = 'Listado';
    $this->selected_id      = 0;
  }

  public function paginationView()
  {
    return 'vendor.livewire.bootstrap';
  }
  public function render()
  {
    if (strlen($this->search) > 0) {
        $data = Permission::where('name','like','%'.$this->search.'%')->paginate($this->pagination);
    }else{
        $data = Permission::orderBy('id','asc')->paginate($this->pagination);
    }
    return view('livewire.permisos.component',['data'=>$data])
        ->extends('layouts.theme.app')
        ->section('content');
  }

  public function store()
  {
    $rules = [
        'name'  => 'required|min:5|unique:permissions,name'
    ];
    $messages = [
        'name.required' => 'El nombre del permiso es requerido',
        'name.min'      => 'El nombre del permiso debe tener al menos 5 caracteres',
        'name.unique'   => 'El permiso ya exixte',
    ];
    $this->validate($rules, $messages);

    Permission::create(['name' => $this->name]);

    $this->resetUI();
    $this->emit('item-added','Registro exitoso!');
  }


  public function edit($id)
  {
    $permiso = Permission::find($id);
    if (isset($permiso)) {
        $this->selected_id  = $permiso->id;
        $this->name         = $permiso->name;
        $this->emit('item-modal-show', 'Mostar modal del Registro!');
        return;
    }else {
        $this->emit('item-error', 'No existe el registro!');
        return;
    }
  }

  public function update()
  {
    $rules = [
        'name'  => "required|min:5|unique:permissions,name,{$this->selected_id}"
    ];
    $messages = [
        'name.required' => 'El nombre del permiso es requerido',
        'name.min'      => 'El nombre del permiso debe tener al menos 5 caracteres',
        'name.unique'   => 'El permiso ya exixte',
    ];
    $this->validate($rules, $messages);

    $permiso = Permission::find($this->selected_id);
    $permiso->name = $this->name;
    $permiso->save();

    $this->resetUI();
    $this->emit('item-updated','Registro Actualizado!');
  }

  protected $listeners = ['deleteRow' => 'destroy'];

  public function destroy($id)
  {
      /* Obtenemos roles asignados este permiso */
      $rolesCount = Permission::find($id)->getRoleNames()->count();
      if ($rolesCount > 0) {
          $this->emit('item-error','No se puede eliminar el permiso porque tiene roles asignados');
          return;
      }

      Permission::find($id)->delete();
      $this->resetUI();
      $this->emit('item-deleted','Registro eliminado con exito!');
  }

  public function resetUI(){
    $this->resetValidation();
    $this->resetPage();

    $this->selected_id  = 0;
    $this->name         = '';
    $this->search       = '';
  }
}

app/Http/Livewire/SearchController.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class SearchController extends Component
{

    public $search;

    public function render()
    {
        return view('livewire.search');
    }
}

resources/views/livewire/denominations/component.blade.php
<div class="row sales layout-top-spacing">
  <div class="col-sm-12">
    <div class="widget widget-chart-one">
      <!-- Begin Titulo de vista y accion agregar -->
      <div class="widget-heading">
        <h5 class="car-title">
          <b>{{ $componentName }} | {{ $pageTitle }}</b>
        </h5>
        @can('Coins_Add')
          <ul class="tabs tab-pills">
            <li>
              <!-- Botton de Agregar -->
              <a href="javascript:void(0)" class="tabmenu p-2 __agregarCoin"
                data-toggle="modal" data-target="#theModal">Agregar
              </a>
            </li>
          </ul>
         @endcan
      </div>
      <!-- End Titulo de vista y accion agregar -->
      <!-- Begin Buscador -->
      @include('common.searchbox')
      <!-- End Buscador -->
      <!-- Begin tabla  -->
      <div class="widget-content">
        <!-- <pre>{{ 'print_r($data)'}} -->
        <div class="table-responsive-md">
          <table class="table table-md table-bordered table-striped">
            <thead>
              <tr class="text-center">
                <th class="table-th">#</th>
                <th class="table-th">TIPO</th>
                <th class="table-th">VALOR</th>
                <th class="table-th">IMAGEN</th>
                @canany(['Coins_Edit','Coins_Delete'])
                  <th class="table-th">ACCIONES</th>
                @endcanany
              </tr>
            </thead>
            <tbody>
              @foreach ($data as $item)
                <tr class="text-center">
                  <td style="width: 50px;">
                      <h6>{{ $item->id}}</h6>
                  </td>
                  <td>
                      <p>{{ $item->type }}</p>
                  </td>
                  </td>
                  <td>
                      <p>$ {{ number_format($item->value,2) }}</p>
                  </td>
                  <td>
                    <span>
                      <!-- Imagen Accessor Modelo Product -->
                      <img src="{{asset('storage/'.$item->image_accessor)}}"
                        alt="imagen ejemplo" height="75" width="80" class="rounded __img-style">
                    </span>
                  </td>
                  <td>
                    @can('Coins_Edit')
                      <!-- Botton de Editar-->
                    <a href="javascript:void(0)"
                        wire:click.prevent="edit({{$item->id}})"
                        class="btn __mtmobile mtmobile bs-tooltip mb-1"
                        data-placement="top"
                        title="Editar">
                      <i class="fas fa-pencil-alt"></i>
                    </a>
                    @endcan
                    @can('Coins_Delete')
                    <!-- Botton de Elimimar -->
                    <a href="javascript:void(0)"
                        onclick="Confirm('{{$item->id}}')"
                        class="btn __mtmobile mtmobile bs-tooltip mb-1"
                        data-placement="top"
                        title="Eliminar">
                      <i class="fas fa-trash"></i>
                    </a>
                    @endcan
                  </td>
                </tr>
              @endforeach
            </tbody>
          </table>
            <div style="display: flex;justify-content: center;">
            {{$data->links()}}
          </div>
        </div>
      </div>
    </div>
  </div>
    <!-- Modal id="#theModal" -->
  @include('livewire.denominations.form')
</div>

<script>
  document.addEventListener("DOMContentLoaded", function(event) {
    /* CoinsController metodo edit */
    window.livewire.on('item-modal-show', msg => {
      console.log('Emit item-modal-show msg:', msg)
      $('#theModal').modal('show');
    });
    /* CoinsController metodo store */
    window.livewire.on('item-added', msg => {
      console.log('Emit item-added msg:', msg)
      $('#theModal').modal('hide');
      swal({
        title: 'Agregado!',
        text: 'El registro ha sido agregado',
        type: 'success',
        timer: 2000
      });
    });
    /* CoinsController metodo update */
    window.livewire.on('item-updated', msg => {
      console.log('Emit item-updated msg:', msg)
      $('#theModal').modal('hide');
      swal({
        title: 'Actualizado!',
        text: 'El registro ha sido actualizado',
        type: 'success',
        timer: 2000
      });
    });
        /* CoinsController metodo delete */
    window.livewire.on('item-deleted', msg => {
      console.log('Emit item-deleted msg:', msg)
      $('#theModal').modal('hide');
      swal({
        title: 'Eliminado!',
        text: 'El registro ha sido eliminado',
        type: 'success',
        timer: 2000
      });
    });

    /* ?? Modal hide show livewire ?? */
    window.livewire.on('modal-show', msg => {
      console.log('Emit modal-show msg:', msg)
      $('#theModal').modal('show');
    });
    window.livewire.on('modal-hide', msg => {
      console.log('Emit modal-hide msg:', msg)
      $('#theModal').modal('hide');
    });

    /* Modal borrar Errors del form */
    $('#theModal').on('hidden.bs.modal', function(e) {
      $('.er').css('display','none');
    });
    /* Modal focus input del form */
    $('#theModal').on('hidden.bs.modal', msg => {
      $('.__focus_active').focus();
    });
  });

  /* metodo eliminar con sweetAlert */
  function Confirm(id) {
    console.log('id,', id)
    swal({
      title: 'Estas Seguro',
      text: '¿Confima para eliminar el registro?',
      type: 'warning',
      showCancelButton: true,
      cancelButtonText: 'Cancelar',
      cancelButtonColor: '#dc3545',
      confirmButtonColor: '#28a745',
      confirmButtonText: 'Eliminar',
            reverseButtons: true,
    }).then(function(result) {
      if (result.value) {
        window.livewire.emit('deleteRow', id)
                swal.close()
      }else if(result.dismiss === Swal.DismissReason.cancel) {
                swal({
                    title: 'Cancelado',
                    text: 'Tu reguistro esta a salvo :)',
                    type: 'error',
                    timer: 2000
                })
            }
    })
  };
</script>

resources/views/livewire/denominations/form.blade.php
@include('common.modalHead')
<div class="row">

    <!-- type -->
    <div class="col-sm-12 col-md-6 col-lg-6">
        <div class="form-group">
            <label>Eligir tipo:</label>
            <div class="input-group">
                <div class="input-group-prepend input-group-text">
                    <span class="far fa-edit"></span>
                </div>
                <select wire:model="type" class="form-control __focus_active">
                    <option value="ELEGIR">Elegir tipo</option>
                    <option value="BILLETE">BILLETE</option>
                    <option value="MONEDA">MONEDA</option>
                    <option value="OTRO">OTRO</option>
                </select>
            </div>
            @error('type')
                <span class="text-danger er">{{ $message }}</span>
            @enderror
        </div>
    </div>

    <!-- value -->
    <div class="col-sm-12 col-md-6 col-lg-6">
        <div class="form-group">
            <label>Escribe el valor: </label>
            <div class="input-group">
                <div class="input-group-prepend input-group-text">
                    <span class="far fa-edit"></span>
                </div>
                <input type="number"
                    wire:model.lazy="value"
                    class="form-control"
                    placeholder="Ingresa valor">
            </div>
            @error('value')
                <span class="text-danger er">{{ $message }}</span>
            @enderror
        </div>
    </div>
    <!-- image -->
    <div class="col-sm-12 col-md-12 col-lg-12 mt-1">
        <label for="image">Agrega una imagen para el valor:</label>
        @if ($image && !is_string($image))
        <img src="{{ $image->temporaryUrl() }}" height="150" width="170" class="rounded __img-style">
        @endif
        <div class="form-group custom-file">
            <input type="file" class="custom-file-input form-control" wire:model.lazy="image" accept="image/jpeg,image/png,image/git">
            <label class="custom-file-label">Nombre: {{$image}}</label>
            @error('image')
            <span class="text-danger er">{{$message}}</span>
            @enderror
        </div>
        @if ($selected_id > 0 && is_string($image))
            <div class="text-center mb-3">
                <img src="{{asset('storage/'.$image)}}" alt="imagen ejemplo" height="150" width="170" class="rounded __img-style">
            </div>
        @endif
    </div>

</div>

@include('common.modalFooter')