routes/web.php
<?php

use App\Http\Controllers\ExportController;
use App\Http\Livewire\AsignarController;
use App\Http\Livewire\CashuotController;
use Illuminate\Support\Facades\Route;
use App\Http\Livewire\CategoriesController;
use App\Http\Livewire\CoinsController;
use App\Http\Livewire\PermisosController;
use App\Http\Livewire\PostController;
use App\Http\Livewire\ProductsController;
use App\Http\Livewire\ReportsController;
use App\Http\Livewire\RolesController;
use App\Http\Livewire\UsersController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::middleware(['auth'])->group(function () {
    // Route::get('/dashboard', ['as' => 'user.dashboard', 'uses' => 'DashboardController@index']);
    Route::get('categories', CategoriesController::class);
    Route::get('products',ProductsController::class);
    Route::get('coins', CoinsController::class);
    Route::get('pos', PostController::class);
    Route::get('roles', RolesController::class);
    Route::get('permisos', PermisosController::class);
    Route::get('asignar', AsignarController::class);
    Route::get('users', UsersController::class);
    Route::get('cashout',CashuotController::class);
    Route::get('reports',ReportsController::class);

});
// Reportes PDF
Route::get('report/pdf/{user}/{type}/{f1}/{f2}', [ExportController::class,'reportPDF']);
Route::get('report/pdf/{user}/{type}', [ExportController::class,'reportPDF']);
//Reportes Excel

app/Http/Livewire/SearchController.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class SearchController extends Component
{

    public $search;

    public function render()
    {
        return view('livewire.search');
    }
}

resources/views/layouts/theme/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">
    <title>SISTEMA DE VENTAS LITE</title>
    <link rel="icon" type="image/x-icon" href="{{asset('assets/img/logo_e/1_letra_e_test.png')}}"/>

    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    @include('layouts.theme.style')
    <!-- END PAGE LEVEL PLUGINS/CUSTOM STYLES -->

</head>
<body class="sidebar-noneoverflow dashboard-sales">
    <!-- BEGIN LOADER -->
    <div id="load_screen"> <div class="loader"> <div class="loader-content">
        <div class="spinner-grow align-self-center"></div>
    </div></div></div>
    <!--  END LOADER -->

    <!--  BEGIN NAVBAR  -->
    @include('layouts.theme.header')
    <!--  END NAVBAR  -->

    <!--  BEGIN MAIN CONTAINER  -->
    <div class="main-container" id="container">

        <div class="overlay"></div>
        <div class="search-overlay"></div>

        <!--  BEGIN SIDEBAR  -->
        @include('layouts.theme.sidebar')
        <!--  END SIDEBAR  -->

        <!--  BEGIN CONTENT AREA  -->
        <div id="content" class="main-content">
            <div class="layout-px-spacing">


                @yield('content')

            </div>
            @include('layouts.theme.footer')
        </div>
        <!--  END CONTENT AREA  -->

    </div>
    <!-- END MAIN CONTAINER -->

    <!-- BEGIN GLOBAL MANDATORY SCRIPTS -->
    @include('layouts.theme.scripts')
    <!-- BEGIN PAGE LEVEL PLUGINS/CUSTOM SCRIPTS -->

</body>
</html>

resources/views/layouts/theme/footer.blade.php
<div class="footer-wrapper">
    <div class="footer-section f-section-1">
        <p class="">Sistema de ventas la Nacional © 2021<a target="_blank" href="https://google.com"></a> - Servido por Emmanuel Perez Luciano.</p>
    </div>
    <div class="footer-section f-section-2">
        <p class="">Version 1.0 <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-heart"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path></svg></p>
    </div>
</div>

resources/views/layouts/theme/header.blade.php
<div class="header-container fixed-top">
  <header class="header navbar navbar-expand-sm ">
    <ul class="navbar-item flex-row __header">
      <li class="theme-logo" style=" margin-right: 20px;">
        <a href="#" class=" text-center __logo">
         <!-- <img src="{{asset('assets/img/logo_v1.jpg')}}"
              class="navbar-logo" alt="logo"> -->
              <div>R-al</div>
              <div>System</div>
        </a>
      </li>
    </ul>

    <a href="javascript:void(0);" class="sidebarCollapse" data-placement="bottom">
      <span class="__icon_search">
        <i class="fas fa-list-ul fa-lg"></i>
    </span>
    </a>

      <!-- Buscador del header en componente-->
    <livewire:search-controller>

    <ul class="navbar-item flex-row navbar-dropdown">

      <li class="nav-item dropdown user-profile-dropdown  order-lg-0 order-1">
        <a href="javascript:void(0);" class="nav-link dropdown-toggle user" id="userProfileDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <div class="icon-container">
            <span style="color:#22b8cf">
              <i class="fas fa-user-circle fa-lg"></i>
            </span>
          </div>
            <!-- <img src="{{ asset('assets/img/profile.png')}}" alt="admin-profile" class="img-fluid"> -->
        </a>
        <div class="dropdown-menu position-absolute animated fadeInUp" aria-labelledby="userProfileDropdown">
          <div class="user-profile-section">
            <div class="media mx-auto">
              <img src="{{ asset('assets/img/profile.png')}}" class="img-fluid mr-2" alt="img">
              <div class="media-body">
                  @if (Auth::user())
                    <h5>{{Auth::user()->name}}</h5>
                    @php
                      $nameRole=Spatie\Permission\Models\Role::find(Auth::user()->role_id);
                    @endphp
                    <p>Perfil: {{$nameRole->name}}</p>
                  @endif
              </div>
            </div>
          </div>
          <div class="dropdown-item">
            <a href="user_profile.html">
              <i class="fas fa-user"></i>
              <span>Mi Perfil</span>
            </a>
          </div>
          <div class="dropdown-item">
            <a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();" data-toggle="tooltip" data-placement="top" title="Tooltip on top">
              <i class="fas fa-sign-out-alt"></i>
              <span>Salir</span>
            </a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
          </div>
        </div>
      </li>
    </ul>
  </header>
</div>
<style>
    .header{
      padding-left:0;
      background: #0F2027 !important;
      background: -webkit-linear-gradient(to top, #2C5364, #203A43, #0F2027) !important;
      background: linear-gradient(to top, #2C5364, #203A43, #0F2027) !important;

    }
    .__header{
        padding-left: 15px !important;
        background-color:#05317d;
        width: 110px;
        height: 80px;
    }
    .__logo{
        /* margin-left:20px; */
        color: white;
        font-size: 20px;
        font-weight: 700;
    }
    .__logo:hover{
        color: #22b8cf;
        width: 38px !important;
        height: 38px !important;
    }
    .navbar .navbar-item .nav-item form.form-inline input.search-form-control {
      background-color: #fff !important;
      padding-top: 12px;
      border: 2px solid #0A65FF !important;
      color: #000 !important;
      border-radius: 20px !important;
    }
    .__icon_search{
        margin-left:15px !important;
        color: #22b8cf;
    }
</style>

resources/views/layouts/theme/scripts.blade.php
<!-- BEGIN GLOBAL MANDATORY SCRIPTS -->
<script src="{{asset('assets/js/libs/jquery-3.1.1.min.js')}}"></script>
<script src="{{asset('bootstrap/js/popper.min.js')}}"></script>
<script src="{{asset('bootstrap/js/bootstrap.min.js')}}"></script>
<script src="{{asset('plugins/perfect-scrollbar/perfect-scrollbar.min.js')}}"></script>
<script src="{{asset('assets/js/app.js')}}"></script>
<script>
    $(document).ready(function() {
        App.init();
    });
    </script>
<script src="{{ asset('assets/js/custom.js')}}"></script>
<script src="{{ asset('plugins/sweetalerts/sweetalert2.min.js')}}"></script>
<script src="{{ asset('plugins/notification/snackbar/snackbar.min.js')}}"></script>
<script src="{{ asset('plugins/nicescroll/nicescroll.js')}}"></script>
<script src="{{ asset('plugins/currency/currency.js')}}"></script>
<script src="{{ asset('plugins/flatpickr/flatpickrv1.js')}}"></script>


<!-- <script src="{{ asset('assets/js/keypress_v1.js')}}"></script>
<script src="{{ asset('assets/js/onscan.js')}}"></script> -->

<script>
    function noty(msg, option = 1){
        Snackbar.show({
            text: msg.toUpperCase(),
            actionText: 'CERRAR',
            actionTextColor: '#ffff',
            backgroundColor: option == 1 ? '#38ba36' : '#c5444c',
            pos: 'top-right'
        });
    }
</script>


@livewireScripts

<!-- END GLOBAL MANDATORY SCRIPTS -->

resources/views/layouts/theme/sidebar.blade.php
<div class="sidebar-wrapper sidebar-theme">

  <div id="compact_submenuSidebar" class="submenu-sidebar" style="display: none!important">
  </div>
  <nav id="compactSidebar">
    <ul class="menu-categories">

      <!-- <li class="active">
          <a href="#dashboard" data-active="true" class="menu-toggle">
              <div class="base-menu">
                  <div class="base-icons">
                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                  </div>
                  <span>PRINCIPAL</span>
              </div>
          </a>
      </li> -->

      @can('Categories_Index')
      <li class="active">
        <a href="{{ url('categories') }}" data-active="false" class="menu-toggle">
          <div class="base-menu">
            <div class="base-icons">
                <i class="fas fa-th-large"></i>
            </div>
            <span>CATEGORIAS</span>
          </div>
        </a>
      </li>
      @endcan

      @can('Products_Index')
      <li>
        <a href="{{ url('products') }}" data-active="false" class="menu-toggle">
          <div class="base-menu">
            <div class="base-icons">
              <i class="fas fa-clipboard"></i>
            </div>
            <span>PRODUCTOS</span>
          </div>
        </a>
      </li>
      @endcan

      @can('Sales_Index')
      <li>
        <a href="{{ url('pos') }}" data-active="false" class="menu-toggle">
          <div class="base-menu">
            <div class="base-icons">
              <i class="fas fa-shopping-cart"></i>
            </div>
            <span>VENTAS</span>
          </div>
        </a>
      </li>
      @endcan

      @can('Roles_Index')
      <li>
        <a href="{{url('roles')}}" data-active="false" class="menu-toggle">
          <div class="base-menu">
            <div class="base-icons">
              <i class="fas fa-key"></i>
            </div>
            <span>ROLES</span>
          </div>
        </a>
      </li>
      @endcan

      @can('Permissions_Index')
      <li>
        <a href="{{url('permisos')}}" data-active="false" class="menu-toggle">
          <div class="base-menu">
            <div class="base-icons">
              <i class="fas fa-check-square"></i>
            </div>
            <span>PERMISOS</span>
          </div>
        </a>
      </li>
      @endcan

      @can('Asignar_Index')
      <li class="asignar">
        <a href="{{url('asignar')}}" data-active="false" class="menu-toggle">
          <div class="base-menu">
            <div class="base-icons">
              <i class="fas fa-eye"></i>
            </div>
            <span>ASIGNAR</span>
          </div>
        </a>
      </li>
      @endcan

      @can('Users_Index')
      <li>
        <a href="{{url('users')}}" data-active="false" class="menu-toggle">
          <div class="base-menu">
            <div class="base-icons">
              <i class="fas fa-users"></i>
            </div>
            <span>USUARIOS</span>
          </div>
        </a>
      </li>
      @endcan

      @can('Coins_Index')
      <li>
        <a href="{{ url('coins') }}" data-active="false" class="menu-toggle">
          <div class="base-menu">
            <div class="base-icons">
              <i class="fas fa-coins"></i>
            </div>
            <span>MONEDAS</span>
          </div>
        </a>
      </li>
      @endcan

      <li>
        <a href="{{url('cashout')}}" data-active="false" class="menu-toggle">
          <div class="base-menu">
            <div class="base-icons">
              <i class="fas fa-dollar-sign"></i>
            </div>
            <span>CORTE CAJA</span>
          </div>
        </a>
      </li>

      <li>
        <a href="{{url('reports')}}" data-active="false" class="menu-toggle">
          <div class="base-menu">
            <div class="base-icons">
              <i class="fas fa-chart-bar"></i>
            </div>
            <span>REPORTES</span>
          </div>
        </a>
      </li>

    </ul>
  </nav>

</div>

resources/views/layouts/theme/style.blade.php
<!-- BEGIN GLOBAL MANDATORY STYLES -->
<script src="{{asset('assets/js/loader.js')}}"></script>
<link href="{{asset('assets/css/loader.css')}}" rel="stylesheet" type="text/css" />
<link href="https://fonts.googleapis.com/css?family=Quicksand:400,500,600,700&display=swap" rel="stylesheet">
<link href="{{asset('bootstrap/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css" />

<link href="{{asset('assets/css/plugins.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/css/structure.css')}}" rel="stylesheet" type="text/css" class="structure" />
<link href="{{asset('assets/css/dashboard/dash_2.css')}}" rel="stylesheet" type="text/css" class="dashboard-sales" />
<!-- END GLOBAL MANDATORY STYLES -->

<!-- BEGIN PAGE LEVEL PLUGINS/CUSTOM STYLES -->
<link href="{{asset('plugins/apex/apexcharts.css')}}" rel="stylesheet" type="text/css">
<link href="{{asset('plugins/sweetalerts/sweetalert2.min.css')}}" rel="stylesheet" type="text/css">
<link href="{{asset('plugins/notification/snackbar/snackbar.min.css')}}" rel="stylesheet" type="text/css">
<link href="{{asset('plugins/flatpickr/flatpickr.dark.css')}}" rel="stylesheet" type="text/css">

<link href="{{asset('plugins/font-icons/fontawesome/css/fontawesome.css')}}" rel="stylesheet" type="text/css">
<link href="{{asset('css/fontawesome.css')}}" rel="stylesheet" type="text/css">
<link href="{{asset('css/custom.css')}}" rel="stylesheet" type="text/css">
<!-- END PAGE LEVEL PLUGINS/CUSTOM STYLES -->

<link href="{{ asset('assets/css/forms/bootstrap-form.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('assets/css/forms/theme-checkbox-radio.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('assets/css/widgets/modules-widgets.css') }}" rel="stylesheet" type="text/css" />

<link href="{{ asset('assets/css/apps/scrumboard.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('assets/css/apps/notes.css') }}" rel="stylesheet" type="text/css" />

<!-- STYLES POR COMPONENTE :V -->
<link href="{{asset('css/style_category.css')}}" rel="stylesheet" type="text/css">
<link href="{{asset('css/style_product.css')}}" rel="stylesheet" type="text/css">
<link href="{{asset('css/style_coins.css')}}" rel="stylesheet" type="text/css">
<link href="{{asset('css/style_pos.css')}}" rel="stylesheet" type="text/css">


<style>
    aside{
        display: none !important;
    }
    .page-item.active .page-link {
        z-index: 3;
        color: #fff;
        background-color: #0A65FF;
        border-color: #0A65FF;
    }
    label{
        color: black !important;
    }
    /* .form-control {
        color:#000 !important;
    } */
    @media (max-width: 480px){
        .__mtmobile{
            margin-bottom: 10px !important;
        }
        .__mbmobile{
            margin-bottom: 10px !important;
            background-color: none !important;
            color: black;
            box-shadow: none
        }
        .hideonsm{
            display: none !important;
        }
        .inblock{
            display: block;
        }
    }
    .__borde {
        border: 2px solid red;
    }
    /* SiderBar background */
    .sidebar-theme #compactSidebar {
        background: #05317d !important;
        width: 110px !important;
    }

    /* Inicio Sidebar */
    .header-container .sidebarCollapse {
        color: #0A65FF !important;
    }
    .base-menu .base-icons {
        color: #ffff !important;
        font-size: 42px !important;
        font-weight: 800 !important;
    }
    .base-menu .base-icons:hover {
        color: #22b8cf !important;
    }
    /* Fin Sidebar */

    /* sweetalerts 2 warning */
    .swal2-icon.swal2-warning {
      font-size: 18px !important;
    }
    .swal2-icon.swal2-info {
      font-size: 18px !important;
    }
    .swal2-popup .swal2-styled.swal2-cancel {
      color: #fff !important;
    }
    /* Boton de Agregar body*/
    .__agregar{
    background-color: #0A65FF !important;
    font-size: 0.95rem !important;
}
    /* Tabla resposnsive body */
    .table-th{
      color: black !important;
    }
    .__img-style{
      object-fit:cover;
      border: 1px solid #ddd;
      border-radius: 4px;
      padding: 5px;
    }

  /* @font-face {
    font-family: 'Material Icons';
    font-style: normal;
    font-weight: 400;
    src: url(plugins/font-icons/iconfont/MaterialIcons-Regular.eot);
    src: local('Material Icons'),
      local('MaterialIcons-Regular'),
      url(plugins/font-icons/iconfont/MaterialIcons-Regular.woff2) format('woff2'),
      url(plugins/font-icons/iconfont/MaterialIcons-Regular.woff) format('woff'),
      url(plugins/font-icons/iconfont/MaterialIcons-Regular.ttf) format('truetype');
  }

  .material-icons {
    font-family: 'Material Icons';
    font-weight: normal;
    font-style: normal;
    font-size: 24px;
    display: inline-block;
    line-height: 1;
    text-transform: none;
    letter-spacing: normal;
    word-wrap: normal;
    white-space: nowrap;
    direction: ltr;
    -webkit-font-smoothing: antialiased;
    text-rendering: optimizeLegibility;
    -moz-osx-font-smoothing: grayscale;
    font-feature-settings: 'liga';
  } */
</style>

@livewireStyles